name: Deploy in main

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Supprimez la stratégie "matrix" inutile ici
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Remove npm lockfile to avoid mixing managers
        run: rm -f package-lock.json

      - name: Install dependencies with Yarn
        run: yarn install --non-interactive

      - name: Build project
        run: yarn build

      - name: Install Wrangler globally
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages deploy dist --project-name=qrcodegenerator
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_DEPLOY_TO_PAGES_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

# r4krC47ODnweLoDPUgHXBeaBIONB2slsO1PIz86E
